### ISSUE TITLE
Keyboard support suggestion

### ISSUE THREAD

**Issue by RaphaelZimmermann** [D4rkTT/Redragon-RGB-SDK#1]
Hey, do you think it's possible to add compatibility for a keyboard that uses Redragon controller? How could I help you doing that?

**Comment by D4rkTT** [comment]
i tried a lot on my keyboard (K552 RGB) but no luck on reversing it sadly :'(
whats model of ur keyboard?

**Comment by RaphaelZimmermann** [comment]
Oh, too bad... mine is Warrior Kane TC235, it's a brazillian branch that uses Redragon's LED controller. People told me that OpenRGB can control some Redragon devices, but I still haven't tried it yet. I hope there's a way to sync the LEDs to games

**Comment by D4rkTT** [comment]
as i know openRGB don't support redragon devices !

**Comment by D4rkTT** [comment]
it supported in ver. 0.21 its working on my K552
