### ISSUE TITLE
How to import Redragon-RGB-SDK.dll into Python !?

### ISSUE THREAD

**Issue by SamueldaCostaAraujoNunes** [D4rkTT/Redragon-RGB-SDK#2]
Hello mate, how are you? I have a Python project, which takes the current Windows color and sends it to my led strip. I also have a mouse redragon snake, and I wanted to take this color and send it to him. But I have a huge difficulty to create a communication between python and Redragon-RGB-SDK.dll. Could you help me with a solution?

The repository I mentioned: https://github.com/SamueldaCostaAraujoNunes/ColorWindowsLed

**Comment by D4rkTT** [comment]
try to use [Python for .NET](http://pythonnet.sourceforge.net/readme.html) or [IronPython](https://ironpython.net/)
